environment=CertifyingPointClouds
conda activate $environment

CUDA_VISIBLE_DEVICES=1 python3 Certify.py --model pointnet2 --dataset modelnet40 --base_classifier_path Pointnet2andDGCNN/trainedModels/pointnetBaseline/FinalModel.pth.tar --sigma 0.05 --certify_method rotationZ --uniform --experiment_name pointnet2RotationZ0.05
CUDA_VISIBLE_DEVICES=1 python3 Certify.py --model pointnet2 --dataset modelnet40 --base_classifier_path Pointnet2andDGCNN/trainedModels/pointnetBaseline/FinalModel.pth.tar --sigma 0.1 --certify_method rotationZ --uniform --experiment_name pointnet2RotationZ0.1
CUDA_VISIBLE_DEVICES=1 python3 Certify.py --model pointnet2 --dataset modelnet40 --base_classifier_path Pointnet2andDGCNN/trainedModels/pointnetBaseline/FinalModel.pth.tar --sigma 0.15 --certify_method rotationZ --uniform --experiment_name pointnet2RotationZ0.15
CUDA_VISIBLE_DEVICES=1 python3 Certify.py --model pointnet2 --dataset modelnet40 --base_classifier_path Pointnet2andDGCNN/trainedModels/pointnetBaseline/FinalModel.pth.tar --sigma 0.2 --certify_method rotationZ --uniform --experiment_name pointnet2RotationZ0.2
CUDA_VISIBLE_DEVICES=1 python3 Certify.py --model pointnet2 --dataset modelnet40 --base_classifier_path Pointnet2andDGCNN/trainedModels/pointnetBaseline/FinalModel.pth.tar --sigma 0.25 --certify_method rotationZ --uniform --experiment_name pointnet2RotationZ0.25
CUDA_VISIBLE_DEVICES=1 python3 Certify.py --model pointnet2 --dataset modelnet40 --base_classifier_path Pointnet2andDGCNN/trainedModels/pointnetBaseline/FinalModel.pth.tar --sigma 0.3 --certify_method rotationZ --uniform --experiment_name pointnet2RotationZ0.3
CUDA_VISIBLE_DEVICES=1 python3 Certify.py --model pointnet2 --dataset modelnet40 --base_classifier_path Pointnet2andDGCNN/trainedModels/pointnetBaseline/FinalModel.pth.tar --sigma 0.35 --certify_method rotationZ --uniform --experiment_name pointnet2RotationZ0.35
CUDA_VISIBLE_DEVICES=1 python3 Certify.py --model pointnet2 --dataset modelnet40 --base_classifier_path Pointnet2andDGCNN/trainedModels/pointnetBaseline/FinalModel.pth.tar --sigma 0.4 --certify_method rotationZ --uniform --experiment_name pointnet2RotationZ0.4
CUDA_VISIBLE_DEVICES=1 python3 Certify.py --model pointnet2 --dataset modelnet40 --base_classifier_path Pointnet2andDGCNN/trainedModels/pointnetBaseline/FinalModel.pth.tar --sigma 0.45 --certify_method rotationZ --uniform --experiment_name pointnet2RotationZ0.45
CUDA_VISIBLE_DEVICES=1 python3 Certify.py --model pointnet2 --dataset modelnet40 --base_classifier_path Pointnet2andDGCNN/trainedModels/pointnetBaseline/FinalModel.pth.tar --sigma 0.5 --certify_method rotationZ --uniform --experiment_name pointnet2RotationZ0.5
CUDA_VISIBLE_DEVICES=1 python3 Certify.py --model pointnet2 --dataset modelnet40 --base_classifier_path Pointnet2andDGCNN/trainedModels/pointnetBaseline/FinalModel.pth.tar --sigma 0.55 --certify_method rotationZ --uniform --experiment_name pointnet2RotationZ0.55
CUDA_VISIBLE_DEVICES=1 python3 Certify.py --model pointnet2 --dataset modelnet40 --base_classifier_path Pointnet2andDGCNN/trainedModels/pointnetBaseline/FinalModel.pth.tar --sigma 0.6 --certify_method rotationZ --uniform --experiment_name pointnet2RotationZ0.6
CUDA_VISIBLE_DEVICES=1 python3 Certify.py --model pointnet2 --dataset modelnet40 --base_classifier_path Pointnet2andDGCNN/trainedModels/pointnetBaseline/FinalModel.pth.tar --sigma 0.65 --certify_method rotationZ --uniform --experiment_name pointnet2RotationZ0.65
CUDA_VISIBLE_DEVICES=1 python3 Certify.py --model pointnet2 --dataset modelnet40 --base_classifier_path Pointnet2andDGCNN/trainedModels/pointnetBaseline/FinalModel.pth.tar --sigma 0.7 --certify_method rotationZ --uniform --experiment_name pointnet2RotationZ0.7
CUDA_VISIBLE_DEVICES=1 python3 Certify.py --model pointnet2 --dataset modelnet40 --base_classifier_path Pointnet2andDGCNN/trainedModels/pointnetBaseline/FinalModel.pth.tar --sigma 0.75 --certify_method rotationZ --uniform --experiment_name pointnet2RotationZ0.75
CUDA_VISIBLE_DEVICES=1 python3 Certify.py --model pointnet2 --dataset modelnet40 --base_classifier_path Pointnet2andDGCNN/trainedModels/pointnetBaseline/FinalModel.pth.tar --sigma 0.8 --certify_method rotationZ --uniform --experiment_name pointnet2RotationZ0.8
CUDA_VISIBLE_DEVICES=1 python3 Certify.py --model pointnet2 --dataset modelnet40 --base_classifier_path Pointnet2andDGCNN/trainedModels/pointnetBaseline/FinalModel.pth.tar --sigma 0.85 --certify_method rotationZ --uniform --experiment_name pointnet2RotationZ0.85
CUDA_VISIBLE_DEVICES=1 python3 Certify.py --model pointnet2 --dataset modelnet40 --base_classifier_path Pointnet2andDGCNN/trainedModels/pointnetBaseline/FinalModel.pth.tar --sigma 0.9 --certify_method rotationZ --uniform --experiment_name pointnet2RotationZ0.9
CUDA_VISIBLE_DEVICES=1 python3 Certify.py --model pointnet2 --dataset modelnet40 --base_classifier_path Pointnet2andDGCNN/trainedModels/pointnetBaseline/FinalModel.pth.tar --sigma 0.95 --certify_method rotationZ --uniform --experiment_name pointnet2RotationZ0.95
CUDA_VISIBLE_DEVICES=1 python3 Certify.py --model pointnet2 --dataset modelnet40 --base_classifier_path Pointnet2andDGCNN/trainedModels/pointnetBaseline/FinalModel.pth.tar --sigma 1 --certify_method rotationZ --uniform --experiment_name pointnet2RotationZ1