python3 Compare3DCertify.py --sigma 0.05  --certify_method rotationX --uniform --experiment_name 64pointnetrotationX0.05
python3 Compare3DCertify.py --sigma 0.1  --certify_method rotationX --uniform --experiment_name 64pointnetrotationX0.1
python3 Compare3DCertify.py --sigma 0.15  --certify_method rotationX --uniform --experiment_name 64pointnetrotationX0.15
python3 Compare3DCertify.py --sigma 0.2  --certify_method rotationX --uniform --experiment_name 64pointnetrotationX0.2
python3 Compare3DCertify.py --sigma 0.25  --certify_method rotationX --uniform --experiment_name 64pointnetrotationX0.25
python3 Compare3DCertify.py --sigma 0.3  --certify_method rotationX --uniform --experiment_name 64pointnetrotationX0.3
python3 Compare3DCertify.py --sigma 0.35  --certify_method rotationX --uniform --experiment_name 64pointnetrotationX0.35
python3 Compare3DCertify.py --sigma 0.4  --certify_method rotationX --uniform --experiment_name 64pointnetrotationX0.4
python3 Compare3DCertify.py --sigma 0.05  --certify_method rotationY --uniform --experiment_name 64pointnetrotationY0.05
python3 Compare3DCertify.py --sigma 0.1  --certify_method rotationY --uniform --experiment_name 64pointnetrotationY0.1
python3 Compare3DCertify.py --sigma 0.15  --certify_method rotationY --uniform --experiment_name 64pointnetrotationY0.15
python3 Compare3DCertify.py --sigma 0.2  --certify_method rotationY --uniform --experiment_name 64pointnetrotationY0.2
python3 Compare3DCertify.py --sigma 0.25  --certify_method rotationY --uniform --experiment_name 64pointnetrotationY0.25
python3 Compare3DCertify.py --sigma 0.3  --certify_method rotationY --uniform --experiment_name 64pointnetrotationY0.3
python3 Compare3DCertify.py --sigma 0.35  --certify_method rotationY --uniform --experiment_name 64pointnetrotationY0.35
python3 Compare3DCertify.py --sigma 0.4  --certify_method rotationY --uniform --experiment_name 64pointnetrotationY0.4
python3 Compare3DCertify.py --sigma 0.1  --certify_method rotationZ --uniform --experiment_name 64pointnetrotationZ0.1
python3 Compare3DCertify.py --sigma 0.2  --certify_method rotationZ --uniform --experiment_name 64pointnetrotationZ0.2
python3 Compare3DCertify.py --sigma 0.3  --certify_method rotationZ --uniform --experiment_name 64pointnetrotationZ0.3
python3 Compare3DCertify.py --sigma 0.4  --certify_method rotationZ --uniform --experiment_name 64pointnetrotationZ0.4
python3 Compare3DCertify.py --sigma 0.5  --certify_method rotationZ --uniform --experiment_name 64pointnetrotationZ0.5
python3 Compare3DCertify.py --sigma 0.6  --certify_method rotationZ --uniform --experiment_name 64pointnetrotationZ0.6
python3 Compare3DCertify.py --sigma 0.7  --certify_method rotationZ --uniform --experiment_name 64pointnetrotationZ0.7
python3 Compare3DCertify.py --sigma 0.8  --certify_method rotationZ --uniform --experiment_name 64pointnetrotationZ0.8
python3 Compare3DCertify.py --sigma 0.9  --certify_method rotationZ --uniform --experiment_name 64pointnetrotationZ0.9
python3 Compare3DCertify.py --sigma 1  --certify_method rotationZ --uniform --experiment_name 64pointnetrotationZ1
